use dotenv::dotenv;
use serenity::prelude::*;
use std::{env, sync::OnceLock};

mod event_handler;
mod response_helper;
mod utils;

/// Whether or not to print messages generated by `debug!`
#[cfg(feature = "debug")]
pub static DEBUG: bool = true;
#[cfg(not(feature = "debug"))]
pub static DEBUG: bool = false;

pub static START_TIME: OnceLock<time::OffsetDateTime> = OnceLock::new();

#[tokio::main]
#[expect(clippy::expect_used, clippy::unwrap_used)]
async fn main() {
    debug!("Init");

    START_TIME.set(time::OffsetDateTime::now_utc()).unwrap();

    // fetch env vars
    dotenv().ok();
    let token = env::var("TOKEN").expect("env variable `TOKEN` should be set");
    #[expect(unused_variables)]
    let application_id =
        env::var("APPLICATION_ID").expect("env variable `APPLICATION_ID` should be set");
    #[expect(unused_variables)]
    let public_key = env::var("PUBLIC_KEY").expect("env variable `PUBLIC_KEY` should be set");

    // Set gateway intents, which decides what events the bot will be notified about
    let intents = GatewayIntents::GUILD_MESSAGES
        // | GatewayIntents::DIRECT_MESSAGES
        | GatewayIntents::MESSAGE_CONTENT;

    // a small thread to poll the gateway, just a test to see if this prevents the
    // slow response to 'cold' commands issue
    tokio::spawn(async move {
        loop {
            tokio::time::sleep(std::time::Duration::from_secs(60)).await;

            if let Some(ctx) = event_handler::CTX.get()
                && let Err(why) = ctx.http.get_gateway().await
            {
                debug!("Error polling gateway: {why:?}");
            }
        }
    });

    // Create a new instance of the Client, logging in as a bot. This will automatically prepend
    // your bot token with "Bot ", which is a requirement by Discord for bot users.
    let mut client = Client::builder(token.clone(), intents)
        .event_handler(event_handler::Handler)
        .await
        .unwrap();

    // Finally, start a single shard, and start listening to events.
    //
    // Shards will automatically attempt to reconnect, and will perform exponential backoff until
    // it reconnects.
    if let Err(why) = client.start().await {
        eprintln!("Client error: {why:?}");
    }
}
